export const fakeFetch = (url) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            if (url === "https://example.com/api/products") {
                resolve({
                    status: 200,
                    message: "Success",
                    data: {
                        products: [
                            {
                                dosage_type: "Tablet",
                                medicine_name: "Spasmex 20 mg/500 mg Drop",
                                content: "Dicyclomine (20mg) + Paracetamol (500mg)",
                                mrp: "22.5",
                                medicine_id: "5V9jvbzLGKcIwCOnnt5Ew",
                                packing_size: "10 ml in 1 packet",
                                size: "1",
                                manufacturer_name: "Hema Laboratories",
                                medicine_type: "drug",
                                availability: "available",
                                image:
                                    "https://res.cloudinary.com/dojsq93dk/image/upload/f_auto,q_auto/u54b5puzp9rizlhyumtg",
                            },
                            {
                                dosage_type: "Tablet",
                                medicine_name: "Aspirin 500 mg",
                                content: "Acetylsalicylic Acid (500mg)",
                                mrp: "10.0",
                                medicine_id: "5HGZ+TIFRaJ1PRz3rvbbA",
                                packing_size: "10 tablets",
                                size: "1",
                                manufacturer_name: "Bayer",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://res.cloudinary.com/dojsq93dk/image/upload/f_auto,q_auto/fh7aar7gzxczcxortcjp",
                            },
                            {
                                dosage_type: "Capsule",
                                medicine_name: "Amoxicillin 250 mg",
                                content: "Amoxicillin (250mg)",
                                mrp: "15.0",
                                medicine_id: "rlLO8MCLONa6do9KdTs9XQ",
                                packing_size: "20 capsules",
                                size: "1",
                                manufacturer_name: "GSK",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://wellonapharma.com/admincms/product_img/product_resize_img/amoxicillin-250mg-capsules_1618818051.jpg",
                            },
                            {
                                dosage_type: "Syrup",
                                medicine_name: "Cetirizine 5 mg/5 ml Syrup",
                                content: "Cetirizine Dihydrochloride (5mg/5ml)",
                                mrp: "12.5",
                                medicine_id: "rgyGF49djXX9L76uzT8KPw",
                                packing_size: "60 ml in 1 bottle",
                                size: "1",
                                manufacturer_name: "Sun Pharmaceuticals",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Cetirizine10.JPG/225px-Cetirizine10.JPG",
                            },
                            {
                                dosage_type: "Injection",
                                medicine_name: "Insulin Glargine 100 IU/ml Injection",
                                content: "Insulin Glargine (100 IU/ml)",
                                mrp: "8.75",
                                medicine_id: "siHnFcYkFJzkI2Dfb2W2IA",
                                packing_size: "1 ml in 1 vial",
                                size: "1",
                                manufacturer_name: "Sanofi",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://images.apollo247.in/pub/media/catalog/product/L/A/LAN0014_1_1.jpg",
                            },
                            {
                                dosage_type: "Cream",
                                medicine_name: "Hydrocortisone 1% Cream",
                                content: "Hydrocortisone (1%)",
                                mrp: "17.0",
                                medicine_id: "tWlD7eTEnRTH+RllfmVtw",
                                packing_size: "15 g in 1 tube",
                                size: "1",
                                manufacturer_name: "Pfizer",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://cpimg.tistatic.com/06787549/b/4/Hydrocortisone-Cream.jpg",
                            },
                            {
                                dosage_type: "Drops",
                                medicine_name: "Artificial Tears Eye Drops",
                                content: "Polyvinyl Alcohol (1.4%)",
                                mrp: "9.5",
                                medicine_id: "YnyUdTNvD8z9Gca6FBEyAQ",
                                packing_size: "10 ml in 1 bottle",
                                size: "1",
                                manufacturer_name: "Johnson & Johnson",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://images.apollo247.in/pub/media/catalog/product/a/r/art0081_1.jpg",
                            },
                            {
                                dosage_type: "Inhaler",
                                medicine_name: "Salbutamol 100 mcg Inhaler",
                                content: "Salbutamol (100 mcg/dose)",
                                mrp: "6.25",
                                medicine_id: "OrjOkv1C8l8VEJX3WdfIpg",
                                packing_size: "200 doses",
                                size: "1",
                                manufacturer_name: "Cipla",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://topazmed.com/image/images/62027dbe8e2f6.jpg?p=full",
                            },
                            {
                                dosage_type: "Gel",
                                medicine_name: "Diclofenac 1% Gel",
                                content: "Diclofenac Sodium (1%)",
                                mrp: "11.0",
                                medicine_id: "QzHHUlgjEGxq+l5ECSLMQ",
                                packing_size: "30 g in 1 tube",
                                size: "1",
                                manufacturer_name: "Novartis",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://2.wlimg.com/product_images/bc-full/2021/11/4073518/diclofenac-sodium-sr-100mg-tab-1637927994-6094300.jpeg",
                            },
                            {
                                dosage_type: "Lotion",
                                medicine_name: "Calamine Lotion",
                                content: "Calamine (15%)",
                                mrp: "13.5",
                                medicine_id: "6UO6b4nt9aWJ7umYt0Tww",
                                packing_size: "100 ml in 1 bottle",
                                size: "1",
                                manufacturer_name: "Reckitt Benckiser",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://images.apollo247.in/pub/media/catalog/product/L/A/LAC0017_1_1.jpg",
                            },
                            {
                                dosage_type: "Suspension",
                                medicine_name: "Paracetamol 125 mg/5 ml Suspension",
                                content: "Paracetamol (125mg/5ml)",
                                mrp: "9.0",
                                medicine_id: "fxWoyqkTbm0rnXfjiNFLA",
                                packing_size: "60 ml in 1 bottle",
                                size: "1",
                                manufacturer_name: "Johnson & Johnson",
                                medicine_type: "drug",
                                availability: "Available",
                                image: "https://images.apollo247.in/pub/media/catalog/product/d/o/dol0027.jpg"
                            },
                            {
                                dosage_type: "Ointment",
                                medicine_name: "Bacitracin 500 units/g Ointment",
                                content: "Bacitracin (500 units/g)",
                                mrp: "7.5",
                                medicine_id: "EtANJcRUGtuoZoYclJ5TA",
                                packing_size: "20 g in 1 tube",
                                size: "1",
                                manufacturer_name: "Pfizer",
                                medicine_type: "drug",
                                availability: "available",
                                image: "https://www.grxstatic.com/d4fuqqd5l3dbz/products/Package_20926.JPG"
                            }
                        ],
                    },
                });
            } else {
                reject({
                    status: 404,
                    message: "Product list not found.",
                });
            }
        }, 100);
    });
};
